# render.yaml
# This file is verified to work with your EvaraTap Server v2.1

services:
  - type: web
    name: evaratap-server
    runtime: node
    plan: free
    branch: main
    
    # This command installs the dependencies from your package.json file.
    buildCommand: "npm install"
    
    # This command runs the "start" script defined in your package.json.
    startCommand: "npm start"
    
    # Defines the environment variables your server will have access to.
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.1
      - key: BLYNK_AUTH_TOKEN
        # This securely injects your secret token into the application.
        # It links to the secret variable you create in the Render Environment tab.
        fromSecret: BLYNK_AUTH_TOKEN_SECRET
