services:
  - type: web
    name: evaratap-blynk-dashboard
    runtime: node
    plan: free
    # The build command explicitly uses npm. The --force flag helps resolve conflicts.
    buildCommand: "npm install --force" 
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: BLYNK_AUTH_TOKEN
        # This value MUST be set in your Render dashboard Environment tab
        sync: false 

